version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nps_php
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nps_db}
      - MYSQL_USER=${MYSQL_USER:-nps_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nps_password}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@nps.com}
      - FROM_NAME=${FROM_NAME:-NPS Survey System}
      - BASE_URL=${BASE_URL:-http://nps.grupopcr.com.pa:8082}
    networks:
      - nps_network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: nps_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nps_db}
      - MYSQL_USER=${MYSQL_USER:-nps_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nps_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - nps_network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nps_phpmyadmin
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER:-nps_user}
      - PMA_PASSWORD=${PMA_PASSWORD:-nps_password}
      - PMA_ARBITRARY=1
      - ALLOW_EMPTY_PASSWORD=0
      - UPLOAD_LIMIT=100M
      - MAX_EXECUTION_TIME=300
      - MEMORY_LIMIT=256M
      - PMA_ABSOLUTE_URI=http://54.94.232.102:8080/
      - PMA_ABSOLUTE_URI_DISCOVER=0
      - PMA_ABSOLUTE_URI_DISCOVER_2=0
      - PMA_ABSOLUTE_URI_DISCOVER_3=0
      - PMA_ABSOLUTE_URI_DISCOVER_4=0
      - PMA_ABSOLUTE_URI_DISCOVER_5=0
      - PMA_ABSOLUTE_URI_DISCOVER_6=0
      - PMA_ABSOLUTE_URI_DISCOVER_7=0
      - PMA_ABSOLUTE_URI_DISCOVER_8=0
      - PMA_ABSOLUTE_URI_DISCOVER_9=0
      - PMA_ABSOLUTE_URI_DISCOVER_10=0
      - PMA_ABSOLUTE_URI_DISCOVER=true
    depends_on:
      - mysql
    networks:
      - nps_network

volumes:
  mysql_data:

networks:
  nps_network:
    driver: bridge 